### ISSUE TITLE
Link from npm to github

### ISSUE THREAD

**Issue by bartbutenaers** [jcronq/node-red-contrib-spline-curve#2]
Hi,
This is a very nice node.  Thanks for sharing it!!

Currently it is not obvious to navigate from npm to this github repository.
Would you be so kind to add the following links to your package.json file:
```
"bugs": {
        "url": "https://github.com/jcronq/node-red-contrib-spline-curve/issues"
    },
    "homepage": "https://github.com/jcronq/node-red-contrib-spline-curve",
    "repository": {
        "type": "git",
        "url": "https://github.com/jcronq/node-red-contrib-spline-curve.git"
    },
```
Then you should see the link in npm (and in flows.nodered.org), similar to this:

![image](https://user-images.githubusercontent.com/14224149/72391607-e39d1500-372d-11ea-943d-83e1a6071384.png)

Thanks !!
Bart

**Comment by jcronq** [comment]
Thank you! I've added the link, and have published the change.
